name: fluro
description: >
  Fluro is a Flutter routing library that adds flexible routing options like wildcards, named
  parameters and clear route definitions.
version: 1.3.5
author: Michael Zhou <zhoulujue@gmail.com>
homepage: https://github.com/zhoulujue/fluro

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0

flutter:
  uses-material-design: false
